In [2]:
import pandas as pd # Option/ALT+Enter

In [3]:
df = pd.read_parquet('../assets/sample.parquet')

In [4]:
df

,email,name,gender,created_at,last_visited_at,last_watched_at,recent_watched,viewed_but_not_started,started_but_not_finished,finished,last_email_notification,last_in_app_notification,last_sms_notification
0,garth.hd167xho@example.net,严鸿灿,female,2022-02-27 22:41:16.419562+00:00,2024-06-04 02:14:16.419563+00:00,2024-04-04 18:47:16.419563+00:00,"[110799, 174828, 155593, 129410, 155055, 12498...","[207388, 221700, 269904, 224910, 245928, 29085...","[363510, 304985, 333202, 306908, 319865, 38578...","[490253, 427979, 485279, 499491, 424777, 48602...",2024-06-23 06:30:16.419566+00:00,2024-06-27 00:25:16.419566+00:00,2024-04-24 05:33:16.419567+00:00
1,marlen.a6aqn616@example.net,汪歆翠,female,2021-05-20 04:54:16.414246+00:00,2024-06-11 17:07:16.414246+00:00,2024-06-03 04:39:16.414246+00:00,"[165739, 128201, 168473, 133844, 129301, 16166...","[296088, 219548, 295688, 275628, 286377, 21878...","[388321, 321767, 329968, 338505, 335293, 35944...","[403087, 483429, 414663, 405228, 468425, 47540...",2024-06-17 03:35:16.414251+00:00,2024-06-22 05:54:16.414252+00:00,2024-06-22 01:59:16.414252+00:00
2,aida.gf3qhygg@example.com,钟晋运,male,2022-10-10 08:13:16.413362+00:00,2024-06-19 11:53:16.413363+00:00,2024-06-29 02:23:16.413363+00:00,"[198953, 101313, 184475, 161792, 146614, 16646...","[212937, 277521, 298945, 264196, 294496, 27593...","[370173, 399603, 307004, 385483, 313985, 36703...","[497748, 474358, 410043, 461982, 428256, 46532...",2024-05-27 08:27:16.413368+00:00,2024-06-21 03:27:16.413368+00:00,2024-06-11 20:22:16.413368+00:00
3,magdalena.if93w4mk@example.org,罗醉珊,male,2019-09-28 18:31:16.413734+00:00,2024-06-26 00:32:16.413734+00:00,2024-05-04 14:07:16.413734+00:00,"[163582, 156251, 163424, 106128, 173157, 19628...","[281455, 243598, 218906, 201215, 271935, 24851...","[383925, 356862, 383031, 383074, 347656, 32769...","[460301, 465014, 400001, 466703, 498134, 44954...",2024-06-15 22:47:16.413739+00:00,2024-06-28 14:23:16.413739+00:00,2024-06-12 21:36:16.413739+00:00
4,malika.k44j8fuk@example.org,陶秋荷,female,2023-08-24 18:13:16.413265+00:00,2024-06-27 07:41:16.413265+00:00,2024-05-30 15:09:16.413265+00:00,"[153222, 117915, 104906, 173119, 132513, 10770...","[275488, 200190, 206277, 233678, 263248, 23170...","[392567, 332758, 371503, 344441, 329280, 38812...","[472101, 458226, 432021, 457483, 432782, 42458...",2024-06-06 13:14:16.413270+00:00,2024-06-21 05:56:16.413270+00:00,2024-05-03 23:31:16.413271+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,margret.xxq4hw5s@example.org,林海亦,male,2024-02-14 22:44:16.416124+00:00,2024-06-01 13:41:16.416124+00:00,2024-06-07 05:39:16.416125+00:00,"[167192, 168461, 160328, 194862, 150757, 15944...","[233563, 279494, 298203, 241039, 239679, 28578...","[376063, 361195, 319252, 373414, 387647, 37522...","[445651, 450602, 471482, 481097, 480176, 40360...",2024-05-28 20:18:16.416129+00:00,2024-06-21 21:32:16.416129+00:00,2024-04-12 06:18:16.416130+00:00
996,leo.t9axqasx@example.com,黄雪娅,unknown,2022-11-09 04:27:16.417547+00:00,2024-06-16 05:47:16.417547+00:00,2024-04-06 19:39:16.417548+00:00,"[133388, 125865, 192541, 105299, 133642, 11442...","[211674, 248088, 219771, 289829, 227328, 25435...","[349174, 379351, 322633, 315025, 342952, 33304...","[427714, 460703, 418560, 452365, 429686, 46761...",2024-06-04 08:28:16.417551+00:00,2024-06-28 17:45:16.417552+00:00,2024-04-11 01:18:16.417552+00:00
997,jesse.2rz1125j@example.org,谢睿轩,male,2023-03-09 04:52:16.418954+00:00,2024-06-03 09:47:16.418954+00:00,2024-04-25 19:45:16.418955+00:00,"[147613, 156265, 158620, 124552, 136984, 13121...","[253832, 271188, 265950, 266452, 285094, 24134...","[331626, 356845, 351318, 318348, 388841, 30327...","[470847, 465997, 448737, 441231]",2024-06-02 02:16:16.418957+00:00,2024-06-14 21:54:16.418957+00:00,2024-05-13 03:49:16.418958+00:00
998,hertha.sq2zh2fj@example.net,李弘邦,female,2024-03-19 02:48:16.419273+00:00,2024-06-03 23:29:16.419273+00:00,2024-06-17 01:19:16.419273+00:00,"[191306, 174987]","[297923, 263857, 236721, 207560, 226456, 22417...","[331758, 322363, 353822, 328705, 305309, 31963...","[494177, 480469, 455590, 468174, 428653, 41607...",2024-06-25 10:39:16.419277+00:00,2024-06-25 16:01:16.419277+00:00,2024-05-26 17:20:16.419278+00:00
999,vickie.zccjqx9y@example.org,许采菡,female,2021-06-25 18:04:16.416756+00:00,2024-06-02 01:54:16.416756+00:00,2024-06-20 12:40:16.416756+00:00,"[101139, 191131, 171950, 115944, 134297, 13135...","[216226, 262114, 291639, 224732, 299409, 25037...","[344155, 301372, 307503, 326085, 321045, 30922...","[431295, 459461, 435686, 418550, 485068, 47596...",2024-06-21 09:10:16.416759+00:00,2024-06-26 02:46:16.416759+00:00,2024-06-06 01:08:16.416760+00:00

In [5]:
df.describe()

,email,name,gender,created_at,last_visited_at,last_watched_at,recent_watched,viewed_but_not_started,started_but_not_finished,finished,last_email_notification,last_in_app_notification,last_sms_notification
count,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
unique,1000,984,3,NaN,NaN,NaN,1000,1000,1000,1000,NaN,NaN,NaN
top,garth.hd167xho@example.net,苏厉轩,female,NaN,NaN,NaN,"[110799, 174828, 155593, 129410, 155055, 12498...","[207388, 221700, 269904, 224910, 245928, 29085...","[363510, 304985, 333202, 306908, 319865, 38578...","[490253, 427979, 485279, 499491, 424777, 48602...",NaN,NaN,NaN
freq,1,2,351,NaN,NaN,NaN,1,1,1,1,NaN,NaN,NaN
mean,NaN,NaN,NaN,2021-12-13 13:02:54.762762+00:00,2024-06-13 20:42:33.642762+00:00,2024-05-14 19:14:32.802763+00:00,NaN,NaN,NaN,NaN,2024-06-06 20:07:38.382766+00:00,2024-06-21 17:47:05.082766+00:00,2024-05-14 05:36:06.282766+00:00
min,NaN,NaN,NaN,2019-07-01 19:52:16.416920+00:00,2024-05-30 03:20:16.416373+00:00,2024-03-31 15:14:16.414898+00:00,NaN,NaN,NaN,NaN,2024-05-15 04:23:16.420776+00:00,2024-06-14 02:30:16.418635+00:00,2024-03-31 04:48:16.415318+00:00
25%,NaN,NaN,NaN,2020-10-06 22:31:46.421138+00:00,2024-06-06 03:42:01.414728+00:00,2024-04-21 17:19:31.416653+00:00,NaN,NaN,NaN,NaN,2024-05-27 07:25:31.418610+00:00,2024-06-18 00:55:16.416199+00:00,2024-04-21 19:18:01.417054+00:00
50%,NaN,NaN,NaN,2021-12-11 18:51:46.419761+00:00,2024-06-13 19:32:46.421133+00:00,2024-05-15 17:13:46.418896+00:00,NaN,NaN,NaN,NaN,2024-06-06 15:27:16.417361+00:00,2024-06-22 00:42:46.418569+00:00,2024-05-14 10:22:46.414543+00:00
75%,NaN,NaN,NaN,2023-03-07 05:03:01.419451+00:00,2024-06-21 10:50:01.419029+00:00,2024-06-07 05:20:31.420206+00:00,NaN,NaN,NaN,NaN,2024-06-18 16:04:01.414526+00:00,2024-06-25 11:15:46.420208+00:00,2024-06-05 02:39:17.004779+00:00
max,NaN,NaN,NaN,2024-03-30 10:26:16.420872+00:00,2024-06-29 01:26:16.417195+00:00,2024-06-29 02:23:16.413363+00:00,NaN,NaN,NaN,NaN,2024-06-29 02:23:16.417438+00:00,2024-06-29 02:12:16.419978+00:00,2024-06-29 01:04:16.526317+00:00